
name: Executar testes unitários

on:
  push:
    branches: [ main ]

jobs:
  teste-unitario:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Instalar dependências
        run: |
          sudo apt-get update && sudo apt-get install -y build-essential python3-pip

      - name: Instalar dependências do projeto
        run: pip install -r requirements.txt

      - name: Executar testes unitários
        run: python3 testes_unitarios.py
